cd ~/nltk_data/chunkers/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/chunkers/maxent_ne_chunker.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/abc.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/alpino.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/biocreative_ppi.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/brown.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/brown_tei.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/cess_cat.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/cess_esp.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/chat80.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/city_database.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/cmudict.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/comparative_sentences.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/comtrans.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/conll2000.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/conll2002.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/conll2007.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/crubadan.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/dependency_treebank.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/europarl_raw.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/floresta.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/framenet_v15.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/framenet_v17.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/gazetteers.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/genesis.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/gutenberg.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/ieer.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/inaugural.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/indian.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/jeita.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/kimmo.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/knbc.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/lin_thesaurus.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/mac_morpho.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/machado.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/masc_tagged.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/movie_reviews.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/mte_teip5.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/names.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/nombank.1.0.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/nonbreaking_prefixes.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/nps_chat.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/omw.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/opinion_lexicon.zip
cd ~/nltk_data/db/
wget http://dev.panlex.org/db/panlex_lite.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/panlex_swadesh.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/paradigms.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/pe08.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/pil.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/pl196x.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/ppattach.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/problem_reports.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/product_reviews_1.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/product_reviews_2.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/propbank.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/pros_cons.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/ptb.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/qc.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/reuters.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/rte.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/semcor.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/senseval.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/sentence_polarity.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/sentiwordnet.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/shakespeare.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/sinica_treebank.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/smultron.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/state_union.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/stopwords.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/subjectivity.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/swadesh.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/switchboard.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/timit.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/toolbox.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/treebank.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/twitter_samples.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/udhr.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/udhr2.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/unicode_samples.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/universal_treebanks_v20.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/verbnet.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/webtext.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/wordnet.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/wordnet_ic.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/words.zip
cd ~/nltk_data/corpora/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/ycoe.zip
cd ~/nltk_data/grammars/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/grammars/basque_grammars.zip
cd ~/nltk_data/grammars/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/grammars/book_grammars.zip
cd ~/nltk_data/grammars/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/grammars/large_grammars.zip
cd ~/nltk_data/grammars/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/grammars/sample_grammars.zip
cd ~/nltk_data/grammars/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/grammars/spanish_grammars.zip
cd ~/nltk_data/help/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/help/tagsets.zip
cd ~/nltk_data/misc/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/misc/perluniprops.zip
cd ~/nltk_data/models/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/models/bllip_wsj_no_aux.zip
cd ~/nltk_data/models/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/models/moses_sample.zip
cd ~/nltk_data/models/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/models/wmt15_eval.zip
cd ~/nltk_data/models/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/models/word2vec_sample.zip
cd ~/nltk_data/sentiment/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/sentiment/vader_lexicon.zip
cd ~/nltk_data/stemmers/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/stemmers/porter_test.zip
cd ~/nltk_data/stemmers/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/stemmers/rslp.zip
cd ~/nltk_data/stemmers/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/stemmers/snowball_data.zip
cd ~/nltk_data/taggers/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/taggers/averaged_perceptron_tagger.zip
cd ~/nltk_data/taggers/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/taggers/averaged_perceptron_tagger_ru.zip
cd ~/nltk_data/taggers/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/taggers/hmm_treebank_pos_tagger.zip
cd ~/nltk_data/taggers/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/taggers/maxent_treebank_pos_tagger.zip
cd ~/nltk_data/taggers/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/taggers/universal_tagset.zip
cd ~/nltk_data/tokenizers/
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/tokenizers/punkt.zip
